
DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS orderRows;

DROP SEQUENCE IF EXISTS seq3;

CREATE SEQUENCE seq3 START WITH 1;

CREATE TABLE orders (id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq3'), orderNumber VARCHAR(255) NOT NULL);

CREATE TABLE orderRows (id BIGINT NOT NULL, itemName VARCHAR(255) NULL, quantity INTEGER NULL, price INTEGER NULL);


